# Generated by Django 4.2.6 on 2023-11-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipes',
            name='pic',
            field=models.ImageField(default='no_image.jpg', upload_to='recipes'),
        ),
    ]
